### test

GET http://localhost:8080/api/v1/test/ HTTP/1.1
Authorization: Basic pascal.galle@gmx.de:password

### get all employees

GET http://localhost:8080/api/v1/users HTTP/1.1
Authorization: Basic admin:password

### get one employee

GET http://localhost:8080/api/v1/employees/23 HTTP/1.1
Authorization: Basic pascal.galle@gmx.de:password

### post on employee

POST http://localhost:8080/api/v1/employees HTTP/1.1
Authorization: Basic pascal.galle@gmx.de:password
content-type: application/json

{
  "firstName": "Bob",
  "lastName": "Galle",
  "emailID": "Bob.galle@gmx.de",
  "password": "password"
}

### delete one employee

DELETE http://localhost:8080/api/v1/employees/24 HTTP/1.1
Authorization: Basic pascal.galle@gmx.de:password

### put on employee

PUT http://localhost:8080/api/v1/employees/25 HTTP/1.1
Authorization: Basic pascal.galle@gmx.de:password
content-type: application/json

{
  "lastName": "Bobble"
}