GET http://localhost:8080/photos

###

GET http://localhost:8080/photos/1

###

DELETE http://localhost:8080/photos/1

###

POST http://localhost:8080/photos HTTP/1.1
content-type: application/json

{
  "filename": "hello.jpg"
}

### Error 

POST http://localhost:8080/photos HTTP/1.1
content-type: application/json

{
  
}